name: GIS Support Request
description: Request for assistance with GIS activities.
title: Page Title, Requested GIS support (i.e. software upgrade, data collection, AGOL login)
labels: ["GIS Support"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: RequestType
    attributes:
        label: What type of GIS Support?
        options:
          - Software Upgrade
          - Data Collection App
          - AGOL login
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISSupportDescription
    attributes:
        label: Describe the support you requested.
        placeholder: A clear and concise description of what you want to happen and what value it will bring. Ex. Change intro text to this "...." because this is more up-to-date. Feel free to attach screenshots or anything you think would help show what you're describing.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: markdown
    attributes:
        value: "### **All website change requests will follow the proper review process.**"
