name: GIS Data Edits Request
description: Request for GIS data editing activities.
title: Page Title, Requested GIS support (i.e. new and/or existing GIS data edits)
labels: ["GIS Tasks"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: RequestType
    attributes:
        label: What type of GIS editing tasks are you requesting?
        options:
          - Edit existing GIS data
          - Edit existing GIS data and publish to web service
          - New GIS data
          - New GIS data for an existing map
          - New GIS data for a new map
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISEditsDescription
    attributes:
        label: Describe the GIS Edits you requested.
        placeholder: A clear and concise description of the GIS edits you need and what value it will bring. Ex. "Edits to this feature class..." Include list of data, marked up maps, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: input
    id: projectCode
    attributes:
        label: Please list Project Code to charge time to. 
        placeholder: Enter project code, or N/A if none
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Thank you for submitting your request!   You will be contacted soon to discuss GIS data editing specifics.**"
