name: GIS Data Edits
description: Request to edit new oe existing GIS data
title: Page Title, Requested GIS Edits (i.e. new and/or existing GIS data edits)
labels: ["GIS Data Edits"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: RequestType
    attributes:
        label: Specificy GIS editing tasks you are requesting.
        options:
          - Edit existing GIS data
          - Edit existing GIS data to update a service
          - New GIS data
          - New GIS data for an existing map
          - New GIS data for a new map
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISEditsDescription
    attributes:
        label: Describe the GIS edits you requested.
        placeholder: A clear and concise description of the GIS edits you need and what value it will bring. Ex. "Edits to this feature class will..." Include list of data, marked up maps, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: input
    id: dueDate
    attributes:
        label: When are these GIS edits needed by? 
        placeholder: Enter the due date here.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How urgent are these edits?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: input
    id: originalDataLocation
    attributes:
        label: Where is existing GIS data is currently stored? 
        placeholder: For existing data, enter path/filename.  For new data, enter N/A.
    validations:
        required: true
  - type: input
    id: newDataLocation
    attributes:
        label: Where to save new GIS data? 
        placeholder: Enter path/filename to save new data.
    validations:
        required: true
- type: input
    id: projectCode
    attributes:
        label: Please list a Project Code to charge time. 
        placeholder: Enter project code, or N/A if none
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Thank you for submitting your request!   You will be contacted soon to discuss GIS data editing specifics.**"
