name: GIS Data Edits Request
description: Request for GIS activities.
title: Page Title, Requested GIS support (i.e. new and/or existing GIS data edits)
labels: ["GIS Tasks"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: RequestType
    attributes:
        label: What type of GIS editing tasks are you requesting?
        options:
          - Edit Data
          - Edit Map
          - Edit Web Map
          - Edit Web Service
          - New Data
          - New Map
          - New Web Map
          - New Web Service
          - Print Map
          - PDF Map
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISEditsDescription
    attributes:
        label: Describe the GIS Edits you requested.
        placeholder: A clear and concise description of the product you want and what value it will bring. Ex. "New map of.... OR  Edits to " Include list of data, marked up maps, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: markdown
    attributes:
        value: "### **You will be contacted to discuss specifics and begin this support.**"
