name: GIS Request
description: Request for GIS edits and/or map products.
title: Page Title, Requested GIS products (i.e. new or existing GIS edits or maps)
labels: ["GIS Edits and Maps"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: MapRequestType
    attributes:
        label: What GIS map product are you requesting?
        options:
          - GeMs conversion
          - Edit existing feature class
          - Edit existing map or map layer
          - New map
          - New web map
          - New feature class or map layer
          - New web service
          - Print map
          - PDF map
    validations:
        required: true
- type: checkboxes
  id: GIS-preferences
  attributes:
    label: Do you prefer GIS work in ArcMap or ArcGIS Pro?
    description: You may select more than one.
    options:
      - label: ArcMap
        required: true
      - label: ArcGIS Pro  
- type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISMapDescription
    attributes:
        label: Describe your requested map product.
        placeholder: A clear and concise description of the GIS map product you want and the purpose.  Also include what value it will bring. Ex. "New map of.... OR  Edits to " Include list of data, marked up maps, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: input
    id: dueDate
    attributes:
        label: When is this map product needed by? 
        placeholder: Enter the due date here.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: input
    id: originalMapLocation
    attributes:
        label: Where is existing GIS map and supporting info currently stored? 
        placeholder: For existing data, enter path and filename.  
    validations:
        required: true
  - type: input
    id: newMapLocation
    attributes:
        label: Where to save new GIS map? 
        placeholder: Enter path and filename to save new data.
    validations:
        required: true
  - type: input
    id: projectCode
    attributes:
        label: Please list Project Code to charge time. 
        placeholder: Enter project code, if applicable
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Thank you for submitting your request!  You will be contacted to discuss mapping specifics soon.**"
