name: GIS Product Request
description: Request for new or existing GIS maps and edits.
title: Page Title, Requested GIS maps and data edits (i.e. new or existing GIS maps)
labels: ["GIS maps and edits"]
assignees:
  - CyndiAndersen, gedouglass
body:
  - type: dropdown
    id: MapRequestType
    attributes:
        label: What GIS product are you requesting?
        options:
          - GeMs conversion
          - General GIS work
          - Edit existing GIS data
          - Edit existing map
          - New feature class
          - New map
          - New web service(s)
          - New web map
          - New web application
          - Print map
          - Create PDF map
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: checkboxes
    id: SignificantInfo
    attributes:
        label: Check all that apply   
        description: Be sure to identify if using ArcMap or ArcGIS Pro
        options:
        - label: ArcMap
        - label: ArcGIS Pro
        - label: This is a StateMap Project
  - type: textarea
    id: GISMapDescription
    attributes:
        label: Describe your requested GIS product.
        placeholder: A clear and concise description of the GIS product you want and the purpose.  Also include what value it will bring. Ex. "New map of.... OR  Edits to " Include list of data, marked up maps, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: input
    id: dueDate
    attributes:
        label: When is this GIS product needed? 
        placeholder: Enter the due date here.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: input
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: input
    id: originalMapLocation
    attributes:
        label: Where is existing GIS, map and/or supporting info currently stored? 
        placeholder: For existing data, enter path and filename.  
    validations:
        required: true
  - type: input
    id: newMapLocation
    attributes:
        label: Where to save new GIS product? 
        placeholder: Enter path and filename to save new data.
    validations:
        required: true
  - type: input
    id: projectCode
    attributes:
        label: Please list Project Code to charge time. 
        placeholder: Enter project code, if applicable
    validations:
        required: false
  - type: markdown
    attributes:
        value: "### **Thank you for submitting your request!  You will be contacted to discuss mapping specifics soon.**"
