name: GIS Support Request
description: Request for assistance with GIS support activities.
title: Page Title, Requested GIS support (i.e. software upgrade, data collection, AGOL login)
labels: ["GIS Support"]
assignees:
  - CyndiAndersen
body:
  - type: dropdown
    id: RequestType
    attributes:
        label: What type of GIS Support?
        options:
          - AGOL access
          - ArcGIS Pro install, license, upgrade, etc.
          - ArcMap install, upgrade, etc.
          - Data collection app
          - Portal access
          - Software upgrade
          - Training
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Please provide information about your request below. This will help with request prioritization.**"
  - type: textarea
    id: GISSupportDescription
    attributes:
        label: Describe the support you requested.
        placeholder: A clear and concise description of what you want to happen and what value it will bring. Ex. "The .... program needs ArcGIS Pro training because several people are transitioning from ArcMap to ArcGIS Pro." Include a list of people, screenshots, or anything you think will support your request.
    validations:
        required: true
  - type: input
    id: dueDate
    attributes:
        label: When is this GIS support needed by... 
        placeholder: Enter the due date here.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If high urgency, please explain.
        placeholder: 
    validations:
        required: false
  - type: textarea
    id: additionalinfo
    attributes:
        label: Additional notes
        placeholder: 
    validations:
        required: false
  - type: input
    id: projectCode
    attributes:
        label: Please list Project Code to charge time. 
        placeholder: Enter project code, or N/A if none
    validations:
        required: true
  - type: markdown
    attributes:
        value: "### **Thank you for submitting your request! You will be contacted to discuss support spacifics soon.**"
